# Generated by Django 3.2.2 on 2021-05-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='snippet',
        ),
    ]
