# Generated by Django 3.1.7 on 2021-05-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=240),
            preserve_default=False,
        ),
    ]
